name: Build and Push Docker Image

on:
  push:
    branches:
      - telegram_bot_v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ksetdekov/trip_choice_optimizer:latest .
          docker push ksetdekov/trip_choice_optimizer:latest
